### ISSUE TITLE
[bug] Mobile browser does not support rotate

### ISSUE THREAD

**Issue by bill3129066** [True-Lucid-Finance/platform-frontend#24]
### See below details
![photo_2023-02-23 14 20 04](https://user-images.githubusercontent.com/8256137/220834212-7dac52d5-44b4-40df-bd0a-48b911627f52.jpeg)

**Comment by andyhsu10** [comment]
Fixed on #26 .
![IMG_B34EA711AAE7-1](https://user-images.githubusercontent.com/12019694/220842400-2e3a3903-d2a6-4bf0-a75f-58c82efdf152.jpeg)
